name: oasis_flutter
description: A flutter client of oasis.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  flutter_webview_plugin: ^0.4.0
  dio: ^5.4.1
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  page_view_indicators: ^2.0.0
  flutter_parsed_text: ^2.2.1
  crypto: ^3.0.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/avatar.png
    - assets/images/icon_close.png
    - assets/images/publish_chat_box.png
    - assets/images/publish_work_line.png
    - assets/images/publish_work_sign.png
    - assets/images/share_qq.png
    - assets/images/share_wechat.png
    - assets/images/main_nav_home_normal.webp
    - assets/images/main_nav_home_hl.webp
    - assets/images/main_nav_discover_normal.webp
    - assets/images/main_nav_discover_hl.webp
    - assets/images/main_nav_message_normal.webp
    - assets/images/main_nav_message_hl.webp
    - assets/images/main_nav_mine_normal.webp
    - assets/images/main_nav_mine_hl.webp
    - assets/images/main_nav_more_normal.webp
    - assets/images/video.png
    - assets/images/video_selected.png
    - assets/images/story.png
    - assets/images/story_selected.png
    - assets/images/money.png
    - assets/images/money_selected.png
    - assets/images/mine.png
    - assets/images/mine_selected.png
    - assets/images/play.png
    - assets/images/pause.png
    - assets/images/shadow_up.png
    - assets/images/shadow_down.png
    - assets/images/default_head.webp
    - assets/images/comment.png
    - assets/images/zan.png
    - assets/images/icon_go_weibo.webp
    - assets/images/icon_go_weibo_pressed.webp
    - assets/images/icon_pyq.webp
    - assets/images/icon_pyq_pressed.webp
    - assets/images/icon_wechat.webp
    - assets/images/icon_wechat_pressed.webp
    - assets/images/icon_weibo.webp
    - assets/images/icon_weibo_pressed.webp
    - assets/images/discover_btn_like.webp
    - assets/images/discover_btn_like_hl.webp
    - assets/images/feed_like.webp
    - assets/images/feed_liked.webp
    - assets/images/feed_comment.webp
    - assets/images/feed_share.webp
    - assets/images/feed_more.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
